#define _HAS_EXCEPTIONS 0

#include "exports.h"
#include <list>
#include <stdio.h>
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include "winsock2.h"
#include "detours.h"
using namespace std;

static const char s_officialIp[16] = "70.5.0.18";
static list<char> s_gameServerIps = {};
static bool s_gfxEnabled = false;
HWND clientHwnd = nullptr;
bool mouseHookInstalled = false;
bool g_isCursorHidden = false;
bool g_stepGetCursorPos = 0;
bool g_isHandlingMouseDown = false;
int rawX = 0, rawY = 0;
int g_stepPanning = 0;
WNDPROC g_realWndProc;

template <typename T>
bool contains(const list<T>& list, const T& element) {
    return !list.empty() && find(list.begin(), list.end(), element) != list.end();
}

static decltype(inet_ntoa)* real_inet_ntoa = inet_ntoa;
// This hook gathers all game server IPs from the server list (some other calls happen before the server list and also after login when connecting to the chat server, but that's fine)
char* WINAPI zzinet_ntoa(_In_ struct in_addr in) {
    char* addr = real_inet_ntoa(in);
    if (strcmp(addr, "211.233.91.10") != 0) { // ignore this IP (always queried on client start)
        s_gameServerIps.push_back(*addr);
    }
    return addr;
}

static decltype(lstrcpynA)* real_lstrcpynA = lstrcpynA;
// Instead of here we could also return the fake IP directly in inet_ntoa but then we have to restore it in the winsock2#connect() call.
LPSTR WINAPI zzlstrcpynA(_Out_writes_(iMaxLength) LPSTR lpString1, _In_ LPCSTR lpString2, _In_ int iMaxLength) {
    if (contains(s_gameServerIps, *lpString2)) {
        s_gameServerIps.clear();
        return real_lstrcpynA(lpString1, s_officialIp, iMaxLength);
    }
    return real_lstrcpynA(lpString1, lpString2, iMaxLength);
}

bool IsCursorHidden() {
    CURSORINFO cursorInfo = { sizeof(cursorInfo) };
    GetCursorInfo(&cursorInfo);
    return cursorInfo.flags == 0;
}

bool AllButtonsUp() {
    return !(GetKeyState(VK_LBUTTON) & 0x8000) && !(GetKeyState(VK_RBUTTON) & 0x8000) && !(GetKeyState(VK_MBUTTON) & 0x8000);
}

HWND GetAionHwnd() {
    if (!clientHwnd) {
        HWND hwnd = GetActiveWindow();
        if (hwnd) {
            char name[64];
            GetClassNameA(hwnd, name, 64);
            if (!strncmp(name, "AIONClient", 10)) {
                clientHwnd = hwnd;
            }
        }
    }
    return clientHwnd;
}
int clientLeft, clientTop;
int MakeMouseMoveWPARAM()
{
    return
        (GetKeyState(VK_LBUTTON) & 0x8000) ? 0x0001 : 0 |
        (GetKeyState(VK_RBUTTON) & 0x8000) ? 0x0002 : 0 |
        (GetKeyState(VK_SHIFT) & 0x8000) ? 0x0004 : 0 |
        (GetKeyState(VK_CONTROL) & 0x8000) ? 0x0008 : 0 |
        (GetKeyState(VK_MBUTTON) & 0x8000) ? 0x0010 : 0 |
        (GetKeyState(VK_XBUTTON1) & 0x8000) ? 0x0020 : 0 |
        (GetKeyState(VK_XBUTTON2) & 0x8000) ? 0x0040 : 0;
}
LPARAM MakeMouseMoveLPARAM(int x, int y) {
    return MAKELPARAM(x - clientLeft, y - clientTop);
}

bool IsWindowedMode() {
    return GetAionHwnd() && ((GetWindowLong(GetAionHwnd(), GWL_STYLE) & WS_CAPTION));
}
RAWINPUT* GetRawInput(HRAWINPUT ri) {

    UINT dwSize;

    GetRawInputData(ri, RID_INPUT, NULL, &dwSize,
        sizeof(RAWINPUTHEADER));
    LPBYTE lpb = new BYTE[dwSize];
    if (lpb == NULL)
    {
        return 0;
    }

    if (GetRawInputData(ri, RID_INPUT, lpb, &dwSize,
        sizeof(RAWINPUTHEADER)) != dwSize) {
        //log("GetRawInputData does not return correct size !");
    }

    RAWINPUT* raw = (RAWINPUT*)lpb;
    return raw;
}

LRESULT CALLBACK RawInputWndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) {
    if (IsWindowedMode()) {
        switch (message) {
        case WM_INPUT:
        {
            g_stepGetCursorPos = 0;

            RAWINPUT* raw = GetRawInput((HRAWINPUT)lParam);
            if (!raw)
                return 0;

            if (raw->header.dwType != RIM_TYPEMOUSE)
                return 0;

            int newX = rawX + raw->data.mouse.lLastX;
            int newY = rawY + raw->data.mouse.lLastY;

            rawX = newX;
            rawY = newY;

            if (g_isCursorHidden) {
                CallWindowProc(g_realWndProc, hWnd, WM_MOUSEMOVE, MakeMouseMoveWPARAM(), MakeMouseMoveLPARAM(rawX, rawY));
                g_stepPanning++;
            }
            else if (!g_isCursorHidden) {
                ClipCursor(nullptr);
                g_stepPanning = 0;
            }
            return 0;
        }
        case WM_LBUTTONDOWN:
        case WM_MBUTTONDOWN:
        case WM_RBUTTONDOWN:
        case WM_XBUTTONDOWN:
        {
            g_isHandlingMouseDown = true;
            LRESULT r = CallWindowProc(g_realWndProc, hWnd, message, wParam, lParam);
            g_isHandlingMouseDown = false;
            return r;
        }
        case WM_MOUSEMOVE:
            if (g_isCursorHidden) {

                // WM_MOUSEMOVE is generated by the WM_INPUT handler
                return 0;
            }
        case WM_CLOSE:
        case WM_DESTROY:
        case WM_NCDESTROY:
        case WM_KILLFOCUS:
            ClipCursor(nullptr);
            break;
        }
    }
    else if (message == WM_INPUT) {
        return 0;
    }
    return CallWindowProc(g_realWndProc, hWnd, message, wParam, lParam);
}

bool g_rawInputFixInstalled = false;

void InstallRawInputFix() {
    HWND hwnd = GetAionHwnd();
    if (!hwnd)
        return;

    g_realWndProc = (WNDPROC)SetWindowLongPtr(hwnd, GWLP_WNDPROC, (LONG_PTR)RawInputWndProc);

    RAWINPUTDEVICE Rid;
    Rid.usUsagePage = 1;
    Rid.usUsage = 2;
    Rid.dwFlags = 0;
    Rid.hwndTarget = hwnd;

    RegisterRawInputDevices(&Rid, 1, sizeof(Rid));

    g_rawInputFixInstalled = true;
}
static decltype(GetCursorPos)* real_GetCursorPos = GetCursorPos;
static decltype(SetCursorPos)* real_SetCursorPos = SetCursorPos;
BOOL WINAPI zzSetCursorPos(_In_ int X, _In_ int Y) {
    BOOL result = TRUE;

    if (!IsWindowedMode())
    {
        result = real_SetCursorPos(X, Y);

        if (GetActiveWindow() == clientHwnd) {
            POINT pt;
            real_GetCursorPos(&pt);
            ScreenToClient(clientHwnd, &pt);

            PostMessage(clientHwnd, WM_MOUSEMOVE, MakeMouseMoveWPARAM(), MAKELPARAM(pt.x, pt.y));
        }
    }
    else
    {
        if (!g_rawInputFixInstalled) {
            InstallRawInputFix();
        }

        if (g_stepGetCursorPos == 0 && g_rawInputFixInstalled && g_isHandlingMouseDown) {
            rawX = X;
            rawY = Y;
        }
    }
    return result;
}
BOOL
WINAPI
zzGetCursorPos(
    _Out_ LPPOINT lpPoint) {

    if (IsWindowedMode())
    {
        g_stepGetCursorPos++;

        if (g_stepGetCursorPos == 1 && g_stepPanning > 0 && g_rawInputFixInstalled && g_isCursorHidden) {
            lpPoint->x = rawX;
            lpPoint->y = rawY;
            return TRUE;
        }
    }
    return real_GetCursorPos(lpPoint);
}
static decltype(SetCursor)* real_SetCursor = SetCursor;
HCURSOR
WINAPI
zzSetCursor(
    _In_opt_ HCURSOR hCursor) {

    if (IsWindowedMode()) {
        bool wasHidden = g_isCursorHidden;

        g_isCursorHidden = !hCursor;

        if (g_rawInputFixInstalled) {
            if (g_isCursorHidden && !wasHidden && GetFocus() == GetAionHwnd()) {
                // lock the cursor pos while hidden
                RECT rc;
                real_GetCursorPos((LPPOINT)&rc);
                rc.right = rc.left + 1;
                rc.bottom = rc.top + 1;
                ClipCursor(&rc);
            }
            else {
                ClipCursor(nullptr);
            }
        }
    }
    return real_SetCursor(hCursor);
}


void EnableHighQualityGraphicsOptions() {
    MEMORY_BASIC_INFORMATION mbi = {};
    if (!VirtualQuery(GetModuleHandle(L"crysystem") + 0x1000, &mbi, sizeof(mbi))) {
        return;
    }

    if (!(mbi.AllocationProtect & 0xF0)) {
        return;
    }

    DWORD oldProtect;
    if (!VirtualProtect(mbi.BaseAddress, mbi.RegionSize, PAGE_EXECUTE_READWRITE, &oldProtect)) {
        return;
    }

    char* c = (char*)mbi.BaseAddress;
    char* end = c + mbi.RegionSize - sizeof(DWORD);

    for (; c < end; c++) {
        DWORD* d = (DWORD*)c;
        if (*d == 1920 * 1200) {
            *d = 4096 * 4096;
            char* e = c - 0x100;
            char* e_end = c + 0x100;
            e_end = min(end, e_end);
            for (; e < e_end; e++) {
                DWORD* d2 = (DWORD*)e;
                if (*d2 == 2560 * 1600) {
                    *d2 = 4096 * 4096;
                    break;
                }
            }
            break;
        }
    }

    VirtualProtect(mbi.BaseAddress, mbi.RegionSize, oldProtect, &oldProtect);
}

static decltype(ChangeDisplaySettingsA)* real_ChangeDisplaySettingsA = ChangeDisplaySettingsA;
LONG WINAPI zzChangeDisplaySettingsA(_In_opt_ DEVMODEA* lpDevMode, _In_ DWORD dwFlags) {
    if (!s_gfxEnabled) {
        EnableHighQualityGraphicsOptions();
        s_gfxEnabled = true;
    }
    return real_ChangeDisplaySettingsA(lpDevMode, dwFlags);
}

bool IsWindows10FallCreatorsUpdateOrLater() {
    DWORD dwDummy;
    DWORD dwFVISize = zzGetFileVersionInfoSizeA("kernel32.dll", &dwDummy);
    LPBYTE lpVersionInfo = new BYTE[dwFVISize];
    if (zzGetFileVersionInfoA("kernel32.dll", 0, dwFVISize, lpVersionInfo)) {
        UINT puLen;
        LPSTR lplpBuffer;
        if (zzVerQueryValueA(lpVersionInfo, "\\", (LPVOID*)& lplpBuffer, &puLen) && puLen == sizeof(VS_FIXEDFILEINFO)) {
            VS_FIXEDFILEINFO* vinfo = (VS_FIXEDFILEINFO*)lplpBuffer;
            int majorVersion = (int)HIWORD(vinfo->dwProductVersionMS);
            int minorVersion = (int)LOWORD(vinfo->dwProductVersionMS);
            int buildNumber = (int)HIWORD(vinfo->dwProductVersionLS);
            return majorVersion == 10 && minorVersion == 0 && buildNumber >= 16299; // 16299 is update version 1709 (Fall Creators Update) which broke the WM_MOUSEMOVE event when dragging the mouse
        }
    }
    return false;
}

void PreloadDXVK()
{
    if (GetModuleHandleW(L"d3d9.dll"))
        return;
    LoadLibraryW(L".\\d3d9.dll");
}

void InstallPatch() {
    PreloadDXVK();
    DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());

    // enable client login to non-official game servers by spoofing game server IP as an official one
    DetourAttach(&(PVOID&)real_inet_ntoa, zzinet_ntoa);
    DetourAttach(&(PVOID&)real_lstrcpynA, zzlstrcpynA);

    // activate camera movement fix for windows 10
    if (IsWindows10FallCreatorsUpdateOrLater()) {
        DetourAttach(&(PVOID&)real_SetCursorPos, zzSetCursorPos);
        DetourAttach(&(PVOID&)real_GetCursorPos, zzGetCursorPos);
        DetourAttach(&(PVOID&)real_SetCursor, zzSetCursor);
    }

    // enable disabled graphics settings on high resolutions
    DetourAttach(&(PVOID&)real_ChangeDisplaySettingsA, zzChangeDisplaySettingsA);

    LONG error = DetourTransactionCommit();
}

BOOL WINAPI DllMain(_In_ HINSTANCE hinstDLL, _In_ DWORD fdwReason, _In_ LPVOID lpvReserved) {
    if (fdwReason == DLL_PROCESS_ATTACH) {
        InstallPatch();
    }
    return TRUE;
}